const Drinks = [
  "Blueberry Limca",
  "Raspberry Limca",
  "Lemon Limca",
  "Orange Limca",
  "Pineapple Limca",
  "Strawberry Limca",
  "Mint Limca",
  "Ginger Limca",
  "Pakola Ice Cream Soda",
  "Cola Next",
  "Fizup",
  "Goverment Cola",
  "Blueberry Slush",
  "Strawberry Slush",
  "Mango Slush",
  "Lemon Slush",
  "Lychee Slush",
  "Cola Slush",
  "Orange Slush",
  "Green Apple Slush",
  "Cherry Slush",
  "Grape Slush",
  "Mango Shake",
  "Banana Shake",
  "Strawberry Shake",
  "Chocolate Shake",
  "Vanilla Shake",
  "Pineapple Shake",
  "Date Shake",
  "Coffee Shake",
  "Cold Coffee",
  "Mint Margarita",
  "Pina Colada",
  "Virgin Mojito",
  "Ab e Dubai Water",
];
